config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "select_report_day#select_day"

  get "select_day", to: "select_report_day#select_day"
  get "select_previous_or_next_day", to: "select_report_day#select_previous_or_next_day"
  get "correct_data_for_month_report", to: "monthly_reports#correct_data_for_month_report"
  get "correct_month_report_data_form", to: "monthly_reports#correct_month_report_data_form"

  post "add_info_to_children", to: "select_report_day#add_info_to_children"
  post "add_info_about_visit", to: "select_report_day#add_info_about_visit"
  post "add_info_about_skip", to: "select_report_day#add_info_about_skip"

  patch "refresh_info_about_visit", to: "select_report_day#refresh_info_about_visit"
  patch "overwrite_children_info", to: "monthly_reports#overwrite_children_info"
  patch "overwrite_child_info", to: "monthly_reports#overwrite_child_info"

  resources :monthly_reports, only: %i[create]
end

app/models/monthly_report.rb
class MonthlyReport < ApplicationRecord
  belongs_to :group
  belongs_to :mentor

  has_many_attached :files

  validates :report_date, presence: true
  validates :data, presence: true
end

app/controllers/monthly_reports_controller.rb
class MonthlyReportsController < ApplicationController
  before_action :define_reasons, only: %i[overwrite_child_info overwrite_children_info]

  def create
    binding.irb
  end

  def correct_data_for_month_report
    group = Group.includes(:children).find(params[:group_id])
    children = group.children.includes(:info_about_visits)
    @info_about_visits = children.map { |child| child.find_info_about_visits_for_correction(params[:month].to_i, params[:year].to_i) }.select { |info| info.any? }

    render partial: "children_list_for_correction", locals: { info_about_visits: @info_about_visits }
  end

  def overwrite_children_info
    if @reasons.include?(params[:commit])
      visits = InfoAboutVisit.where(id: params[:visit_ids])

      visits.each do |visit|
        visit.update_visit_info(params[:commit])
        turbo_update(visit.child, visit.date, visit)
      end
    else
      redirect_to root_path
    end
  end

  def overwrite_child_info
    if @reasons.include?(params[:reason])
      visit = InfoAboutVisit.find(params[:visit_id])

      visit.update_visit_info(params[:reason])
      turbo_update(visit.child, visit.date, visit)
    else
      redirect_to root_path
    end
  end

  def correct_month_report_data_form
    @mentor = Mentor.includes(:groups).find(1)
    @groups = @mentor.groups

    render partial: "correct_month_report_data_form", locals: { groups: @groups }
  end

  private

  def define_reasons
    @reasons = ["sick", "vacation", "other"]
  end

  def turbo_update(child, date, visit)
    respond_to do |format|
      format.turbo_stream do
        Turbo::StreamsChannel.broadcast_update_to(
          child.group.mentors,
          target: "info_about_visit_#{ visit.id }",
          partial: "monthly_reports/overwrite_info_about_visit_reason",
          locals: { visit: visit }
        )
      end
    end
  end
end

app/views/monthly_reports/_children_list_for_correction.html.erb
<%= turbo_frame_tag "correct_month_report_data" do %>
  <%= link_to "Back to form", correct_month_report_data_form_path, class: "btn btn-primary col-12 mb-2", data: { turbo_frame: "correct_month_report_data" } %>

  <% info_about_visits.each do |visits| %>
    <div class="accordion my-0 p-0" id="accordionPanelsStayOpenExample">
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse-<%= visits.first.child.id %>" aria-expanded="true" aria-controls="panelsStayOpen-collapse-<%= visits.first.child.id %>">
            <div class="m-0 p-0 d-flex flex-column">
              <p class="m-0 p-0 lh-1"><%= visits.first.child.first_name %></p>
              <p class="m-0 p-0 lh-1"><%= visits.first.child.middle_name %></p>
              <p class="m-0 p-0 lh-1"><%= visits.first.child.last_name %></p>
            </div>
          </button>
        </h2>
        <div id="panelsStayOpen-collapse-<%= visits.first.child.id %>" class="accordion-collapse collapse show">
          <div class="accordion-body">
            <%= form_with url: overwrite_children_info_path, method: :patch, data: { turbo: true } do |form| %>
              <table class="table table-sm text-center" id="visit">
                <tr>
                  <th>Checkbox</th>
                  <th>Date</th>
                  <th>Selectable</th>
                </tr>
                <% visits.each do |visit| %>
                  <tr id="visit_<%= visit.id %>">
                    <td>
                      <div class="d-flex justify-content-center m-0 p-0">
                        <input class="form-check-input" type="checkbox" id="visit_checkbox_<%= visit.id %>" value="<%= visit.id %>" name="visit_ids[]">
                      </div>
                    </td>
                    <td>
                      <%= correct_date(visit.date) %>
                    </td>
                    <td id="info_about_visit_<%= visit.id %>" class="row">
                      <div class="dropdown col-12">
                        <button class="btn btn-primary btn-sm col-12 mx-auto" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                          <%= visit.reason %>
                        </button>
                        <ul class="dropdown-menu">
                          <li>
                            <%= link_to "sick", overwrite_child_info_path(reason: "sick", visit_id: visit.id), data: { turbo_method: "patch" }, class: "text-decoration-none d-flex justify-content-center my-3 text-white" %>
                          </li>
                          <li>
                            <%= link_to "vacation", overwrite_child_info_path(reason: "vacation", visit_id: visit.id), data: { turbo_method: "patch" }, class: "text-decoration-none d-flex justify-content-center my-3 text-white" %>
                          </li>
                          <li>
                            <%= link_to "other", overwrite_child_info_path(reason: "other", visit_id: visit.id), data: { turbo_method: "patch" }, class: "text-decoration-none d-flex justify-content-center my-3 text-white" %>
                          </li>
                        </ul>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </table>
              <div class="m-0 p-0 d-flex flex-row">
                <%= form.submit "sick", class: "btn btn-primary p-1 mx-1 my-0 w-100" %>
                <%= form.submit "vacation", class: "btn btn-primary p-1 mx-1 my-0 w-100" %>
                <%= form.submit "other", class: "btn btn-primary p-1 mx-1 my-0 w-100" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/monthly_reports/_correct_month_report_data_form.html.erb
<%= turbo_frame_tag "correct_month_report_data" do %>
  <%= form_with url: correct_data_for_month_report_path, method: :get, data: { turbo_frame: "correct_month_report_data" } do |form| %>
    <div class="m-0 p-0 row">
      <div class="mx-auto my-0 p-0 d-flex flex-column col-8">
        <%= form.label :year %>
        <%= form.select :year, (2025..(Date.current.year + 1)).to_a, selected: Date.current.year %>
        <%= form.label :month %>
        <%= form.select :month, [*1..12], selected: Date.current.month %>
        <%= form.label :group_id %>
        <%= form.select :group_id, groups.map { |g| [g.title, g.id] } %>
        <%= form.submit "Next", class: "btn btn-primary mt-2" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/monthly_reports/_overwrite_info_about_visit_reason.html.erb
<div class="dropdown col-12">
  <button class="btn btn-primary btn-sm col-12 mx-auto" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    <%= visit.reason %>
  </button>
  <ul class="dropdown-menu">
    <li>
      <%= link_to "sick", overwrite_child_info_path(reason: "sick", visit_id: visit.id), data: { turbo_method: "patch" }, class: "text-decoration-none d-flex justify-content-center my-3 text-white" %>
    </li>
    <li>
      <%= link_to "vacation", overwrite_child_info_path(reason: "vacation", visit_id: visit.id), data: { turbo_method: "patch" }, class: "text-decoration-none d-flex justify-content-center my-3 text-white" %>
    </li>
    <li>
      <%= link_to "other", overwrite_child_info_path(reason: "other", visit_id: visit.id), data: { turbo_method: "patch" }, class: "text-decoration-none d-flex justify-content-center my-3 text-white" %>
    </li>
  </ul>
</div>