config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "select_report_day#select_day"

  get "select_day", to: "select_report_day#select_day"
  get "select_previous_or_next_day", to: "select_report_day#select_previous_or_next_day"
  get "correct_data_for_month_report", to: "monthly_reports#correct_data_for_month_report"
  get "correct_month_report_data_form", to: "monthly_reports#correct_month_report_data_form"

  post "add_info_to_children", to: "select_report_day#add_info_to_children"
  post "add_info_about_visit", to: "select_report_day#add_info_about_visit"
  post "add_info_about_skip", to: "select_report_day#add_info_about_skip"

  patch "refresh_info_about_visit", to: "select_report_day#refresh_info_about_visit"
  patch "overwrite_children_info", to: "monthly_reports#overwrite_children_info"
  patch "overwrite_child_info", to: "monthly_reports#overwrite_child_info"

  resources :monthly_reports, only: %i[create]
end

app/controllers/select_report_day_controller.rb
class SelectReportDayController < ApplicationController
  before_action :check_inputed_day, only: %i[ select_day select_previous_or_next_day ]
  before_action :find_child, except: %i[ select_day select_previous_or_next_day add_info_to_children ]
  before_action :correct_day, except: %i[ select_day select_previous_or_next_day add_info_to_children ]

  def select_day
    @mentor = Mentor.includes(:groups).find(1)
    @groups = @mentor.groups
    @day = params[:day]

    render "select_day", locals: { mentor: @mentor, groups: @groups, day: @day }
  end

  def select_previous_or_next_day
    @mentor = Mentor.includes(:groups).find(1)
    @groups = @mentor.groups

    if params[:choosing_day] == "next" || params[:choosing_day] == "previous"
      params[:choosing_day] == "next" ? @day = params[:day].to_date + 1.day : @day = params[:day].to_date - 1.day
      render "select_day", locals: { mentor: @mentor, groups: @groups, day: @day }
    else
      redirect_to root_path
    end
  end

  def add_info_to_children
    if params[:child_ids].present? && params[:commit].present? && params[:day].present?
      children = Child.where(id: params[:child_ids])

      if params[:commit] == "Mark as visited"
        children.each do |child|
          if child.info_already_present?(params[:day].to_date)
            child.refresh_visit_info(params[:day].to_date)
            turbo_update(child, params[:day].to_date)
          else
            child.create_visit_info(params[:day].to_date)
            turbo_update(child, params[:day].to_date)
          end
        end
      elsif params[:commit] == "Mark as skiped"
        children.each do |child|
          if child.info_already_present?(params[:day].to_date)
            child.refresh_visit_info(params[:day].to_date)
            turbo_update(child, params[:day].to_date)
          else
            child.create_skip_info(params[:day].to_date)
            turbo_update(child, params[:day].to_date)
          end
        end
      else
        redirect_to root_path
      end
    end
  end

  def add_info_about_visit
    if @date.present? && @child.present?
      @child.create_visit_info(@date)
      turbo_update(@child, @date)
    else
      redirect_to root_path
    end
  end

  def add_info_about_skip
    if @date.present? && @child.present?
      @child.create_skip_info(@date)
      turbo_update(@child, @date)
    else
      redirect_to root_path
    end
  end

  def refresh_info_about_visit
    if @date.present? && @child.present?
      @child.refresh_visit_info(@date)
      turbo_update(@child, @date)
    else
      redirect_to root_path
    end
  end

  private

  def find_child
    @child = Child.find(params[:child])
  end

  def correct_day
    @date = clean_date_param(params[:day]).to_date if params[:day].present?
  end

  def turbo_update(child, date)
    respond_to do |format|
      format.turbo_stream do
        Turbo::StreamsChannel.broadcast_update_to(
          "#{ child.group.title }_children_list_#{ date }",
          target: "child_#{ child.id }",
          partial: "select_report_day/overwrite_info_about_visit",
          locals: { child: child, day: params[:day] }
        )
      end
    end
  end

  def clean_date_param(param)
    param.gsub(/.*?(\b\d{4}-\d{2}-\d{2}\b).*?/, '\1') if param.present?
  end

  def check_inputed_day
    cleaned_params_day = params[:day].present? ? clean_date_param(params[:day]) : ""

    valid_date = begin
                           Date.parse(cleaned_params_day)
                         rescue ArgumentError
                           nil
                         end

    if valid_date && valid_date >= Date.new(2025, 1, 1) && valid_date <= Time.current.to_date + 5.days
      params[:day] = valid_date.strftime("%Y-%m-%d")
    else
      params[:day] = Time.current.to_date.strftime("%Y-%m-%d")
    end
  end
end

app/helpers/select_report_day_helper.rb
module SelectReportDayHelper
  def max_available_day(day)
    day.to_date + 5.days
  end

  def child_info_about_visit(child, day)
    if child.info_about_visits.find_by(date: day.to_date).present?
      refresh_info_about_visit(child, day)
    else
      add_info_about_visit(child, day)
    end
  end

  def bg_color_by_visit(child, day)
    if child.info_already_present?(day) && child.today_visited?(day)
      "bg-success"
    elsif child.info_already_present?(day) && !child.today_visited?(day)
      "bg-danger"
    else
      ""
    end
  end

  def correct_date(day)
    day.strftime("%d.%m.%Y")
  end

  private

  def refresh_info_about_visit(child, day)
    render partial: "select_report_day/refresh_info_about_visit", locals: { child: child, day: day }
  end

  def add_info_about_visit(child, day)
    render partial: "select_report_day/add_info_about_visit", locals: { child: child, day: day }
  end
end

app/views/select_report_day/_add_info_about_visit.html.erb
<div class="m-0 p-0 d-flex flex-row">
  <%= link_to add_info_about_visit_path(params: { child: child, day: day }), data: { turbo_method: "post" }, class: "link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-check-circle mt-2 mb-0 me-3 ms-0 p-0" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
      <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
    </svg>
  <% end %>
  <%= link_to add_info_about_skip_path(params: { child: child, day: day }), data: { turbo_method: "post" }, class: "link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-x-circle mt-2 mb-0 mx-0 p-0" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
      <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
    </svg>
  <% end %>
</div>

app/views/select_report_day/_overwrite_info_about_visit.html.erb
<td class="<%= bg_color_by_visit(child, day.to_date) %>">
  <div class="d-flex justify-content-center mt-2 mb-0 mx-0 p-0">
    <input class="form-check-input" type="checkbox" id="child_checkbox_<%= child.id %>" value="<%= child.id %>" name="child_ids[]">
  </div>
</td>
<td class="<%= bg_color_by_visit(child, day.to_date) %>">
  <div class="m-0 p-0 d-flex flex-column">
    <p class="m-0 p-0 lh-1"><%= child.first_name %></p>
    <p class="m-0 p-0 lh-1"><%= child.middle_name %></p>
    <p class="m-0 p-0 lh-1"><%= child.last_name %></p>
  </div>
</td>
<td class="<%= bg_color_by_visit(child, day.to_date) %>"><%= child_info_about_visit(child, day) %></td>

app/views/select_report_day/_refresh_info_about_visit.html.erb
<%= link_to refresh_info_about_visit_path(params: { child: child, day: day }),data: { turbo_method: "patch" }, class: "link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" do %>
  <% if child.today_visited?(day) %>
    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="white" class="bi bi-check-circle mt-2 mb-0 mx-0 p-0" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
        <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
      </svg>
  <% else %>
    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="white" class="bi bi-x-circle mt-2 mb-0 mx-0 p-0" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
      <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
    </svg>
  <% end %>
<% end %>

app/views/select_report_day/select_day.html.erb
<%= turbo_frame_tag "children_list" do %>
  <%= turbo_stream_from mentor %>
  <div class="mb-0 mt-3 p-0 col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4 col-xxl-4 mx-auto d-flex flex-column">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Generate monthly report
    </button>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-scrollable modal-fullscreen">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Correct month report data</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
          </div>
          <div class="modal-body col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4 col-xxl-4 mx-auto d-flex flex-column">
            <%= turbo_frame_tag "correct_month_report_data" do %>
              <%= form_with url: correct_data_for_month_report_path, method: :get, data: { turbo_frame: "correct_month_report_data" } do |form| %>
                <div class="m-0 p-0 row">
                  <div class="mx-auto my-0 p-0 d-flex flex-column col-8">
                    <%= form.label :year %>
                    <%= form.select :year, (2025..(Date.current.year + 1)).to_a, selected: Date.current.year %>
                    <%= form.label :month %>
                    <%= form.select :month, [*1..12], selected: Date.current.month %>
                    <%= form.label :group_id %>
                    <%= form.select :group_id, groups.map { |g| [g.title, g.id] } %>
                    <%= form.submit "Next", class: "btn btn-primary mt-2" %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid my-3 mx-0 p-0 row">
    <div class="container-fluid m-0 py-1 px-1 col-12 d-flex justify-content-center">
      <%= form_with url: select_day_path, method: :get, data: { turbo_frame: "children_list" } do |form| %>
        <div class="m-0 p-0 d-flex flex-row">
          <label for="day" class="me-2 d-flex align-items-center">Report day:</label>
          <input type="date" id="day" name="day" value="<%= day %>" min="2025-01-01" max="<%= max_available_day(Time.current.to_date) %>" />
          <%= form.submit "Choose day", class: "btn btn-primary p-1 ms-1 me-1 my-0" %>
        </div>
      <% end %>
    </div>

    <div class="container-fluid m-0 py-1 px-1 col-12 d-flex justify-content-center">
      <div class="m-0 p-0 d-flex flex-column">
        <p class="m-0 p-0 lh-1">Mentor: <b><%= mentor.first_name %></b></p>
      </div>
    </div>

    <div class="m-0 pb-2 pt-0 px-0 d-flex flex-row justify-content-center align-items-center">
      <%= link_to select_previous_or_next_day_path(params: { choosing_day: "previous", day: day }), data: { turbo_frame: "children_list" }, class: "link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-caret-left-fill" viewBox="0 0 16 16">
          <path d="m3.86 8.753 5.482 4.796c.646.566 1.658.106 1.658-.753V3.204a1 1 0 0 0-1.659-.753l-5.48 4.796a1 1 0 0 0 0 1.506z"/>
        </svg>
      <% end %>
      <p class="mx-3 my-0 p-0">Current day: <b><%= correct_date(day.to_date) %></b></p>
      <%= link_to select_previous_or_next_day_path(params: { choosing_day: "next", day: day }), data: { turbo_frame: "children_list" }, class: "link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-caret-right-fill" viewBox="0 0 16 16">
          <path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z"/>
        </svg>
      <% end %>
    </div>

    <% groups.each do |group| %>
      <div class="row p-0 m-0">
        <div class="my-0 p-0 col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4 col-xxl-4 mx-auto d-flex flex-column">
          <div class="accordion" id="accordionExample<%= group.id %>">
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button p-3" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne<%= group.id %>" aria-expanded="true" aria-controls="collapseOne<%= group.id %>">
                  <div class="container-fluid m-0 py-1 px-1 col-12 d-flex justify-content-center">
                    <div class="m-0 p-0 d-flex flex-column">
                      <p class="m-0 p-0 lh-1">Group title: <b><%= group.title %></b></p>
                    </div>
                  </div>
                </button>
              </h2>
              <div id="collapseOne<%= group.id %>" class="accordion-collapse collapse show" data-bs-parent="#accordionExample<%= group.id %>">
                <div class="accordion-body">
                  <div class="container-fluid m-0 py-1 px-1 col-12 d-flex justify-content-center">
                    <%= turbo_stream_from "#{ group.title }_children_list_#{ day.to_date }" %>
                    <%= form_with url: add_info_to_children_path(params: { day: day }), method: :post, data: { turbo: true } do |form| %>
                      <table class="table table-sm text-center" id="children">
                        <tr>
                          <th>Checkbox</th>
                          <th>Child name</th>
                          <th>Add Info</th>
                        </tr>
                        <% group.children.each do |child| %>
                          <tr id="child_<%= child.id %>">
                            <td class="<%= bg_color_by_visit(child, day.to_date) %>">
                              <div class="d-flex justify-content-center mt-2 mb-0 mx-0 p-0">
                                <input class="form-check-input" type="checkbox" id="child_checkbox_<%= child.id %>" value="<%= child.id %>" name="child_ids[]">
                              </div>
                            </td>
                            <td class="<%= bg_color_by_visit(child, day.to_date) %>">
                              <div class="m-0 p-0 d-flex flex-column">
                                <p class="m-0 p-0 lh-1"><%= child.first_name %></p>
                                <p class="m-0 p-0 lh-1"><%= child.middle_name %></p>
                                <p class="m-0 p-0 lh-1"><%= child.last_name %></p>
                              </div>
                            </td>
                            <td class="<%= bg_color_by_visit(child, day.to_date) %>"><%= child_info_about_visit(child, day) %></td>
                          </tr>
                        <% end %>
                      </table>
                      <button type="button" class="btn btn-primary p-1 m-0 w-100" data-bs-toggle="modal" data-bs-target="#exampleModal<%= group.id %>">
                        Mark as...
                      </button>
                      <div class="modal fade" id="exampleModal<%= group.id %>" tabindex="-1" aria-labelledby="exampleModalLabel<%= group.id %>" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h1 class="modal-title fs-5" id="exampleModalLabel<%= group.id %>">Mark as...</h1>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                              <div class="m-0 p-0 d-flex flex-row">
                                <%= form.submit "Mark as visited", class: "btn btn-primary p-1 mx-1 my-0 w-100", "data-bs-dismiss" => "modal" %>
                                <%= form.submit "Mark as skiped", class: "btn btn-primary p-1 mx-1 my-0 w-100", "data-bs-dismiss" => "modal" %>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>